### PR TITLE
added loader at center 

### PR DESCRIPTION
**Pull request by Darainn**

### CODE REVIEW

**Comment by Darainn** [comment]
@ggautamgoyalg pls merge this and label as hacktoberfest

**Comment by Darainn** [comment]
@ggautamgoyalg add hacktoberfest label to your repo

**Comment by ggautamgoyalg** [comment]
Add ss/video of changes done

**Comment by Darainn** [comment]
image

my laptop is on dark theme but the loader is now centered

**Comment by Darainn** [comment]
image
@ggautamgoyalg add label in your repo also for hacktoberfest in settings

**Comment by ggautamgoyalg** [comment]
ok

**Comment by ggautamgoyalg** [comment]
done
check that once

**Comment by Darainn** [comment]
image
still not verified you have to add the hacktoberfest label in your repo like below

image

**Pull request merged**
